export const SIGN_UP = "SIGN_UP"
export const SIGN_SUCCESS = "SIGN_SUCCESS"
export const SIGN_UP_FAILED = "SIGN_UP_FAILED"

export const SIGN_IN = "SIGN_IN"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const SIGN_IN_FAILED = "SIGN_IN_FAILED"
export const SIGN_OUT = "SIGN_OUT"
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED"
export const SET_CURRENT_USER_SIGN_OUT = "SET_CURRENT_USER_SIGN_OUT"



export const GET_KITCHENS = "GET_KITCHENS"
export const KITCHENS_RECEIVED= "KITCHENS_RECEIVED"
export const KITCHENS_FAILED= "KITCHENS_FAILED"
export const ADD_KITCHENS = "ADD_KITCHENS"
export const KITCHENS_ADDED= "KITCHENS_ADDED"
export const DELETE_KITCHENS = "DELETE_KITCHENS"
export const DELETE_KITCHENS_SUCCESS = "DELETE_KITCHENS_SUCCESS"

export const EDIT_KITCHEN = "EDIT_KITCHEN"
export const KITCHEN_EDIT_SUCCESS = "KITCHEN_EDIT_SUCCESS"
export const KITCHEN_EDIT_FAILED = "KITCHEN_EDIT_FAILED"

export const GET_RESTAURANTS = "GET_RESTAURANTS"
export const GET_RESTAURANTS_ID = "GET_RESTAURANTS_ID"
export const RESTAURANTS_RECEIVED= "RESTAURANTS_RECEIVED"
export const RESTAURANTS_FAILED= "RESTAURANTS_FAILED"
export const RESTAURANTS_ID_RECEIVED= "RESTAURANTS_ID_RECEIVED"
export const RESTAURANTS_ID_FAILED= "RESTAURANTS_ID_FAILED"
export const ADD_RESTAURANT = "ADD_RESTAURANT"
export const RESTAURANT_ADD_SUCCESS = "RESTAURANT_ADD_SUCCESS"
export const RESTAURANT_ADD_FAILED = "RESTAURANT_ADD_FAILED"
export const DELETE_RESTAURANT = "DELETE_RESTAURANT"
export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS"

export const EDIT_RESTAURANT = "EDIT_RESTAURANT"
export const RESTAURANT_EDIT_SUCCESS = "RESTAURANT_EDIT_SUCCESS"
export const RESTAURANT_EDIT_FAILED = "RESTAURANT_EDIT_FAILED"

export const GET_REVIEW = "GET_REVIEW"
export const REVIEW_RECEIVED = "REVIEW_RECEIVED"
export const ADD_REVIEW = "ADD_REVIEW"
export const REVIEW_ADDED = "REVIEW_ADDED"
export const REVIEW_FAILED = "REVIEW_FAILED"
export const DELETE_REVIEW = "DELETE_REVIEW"
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"


export const ADD_ORDER = "ADD_ORDER"
export const ORDER_ADDED = "ORDER_ADDED"
export const ORDER_ADD_FAILED = "ORDER_ADD_FAILED"
export const GET_ORDER = "GET_ORDER"
export const ORDER_RECEIVED = "ORDER_RECEIVED"
export const ORDER_RECEIVED_FAILED = "ORDER_RECEIVED_FAILED"

export const GET_COORDINATES = "GET_COORDINATES"
export const COORDINATES_RECEIVED = "COORDINATES_RECEIVED"
export const COORDINATES_FAILED = "COORDINATES_FAILED"

